url: "https://hao-w.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""
permalink: /:year/:month/:day/:title
timezone: America/New_York
title: "Hao Wu's Personal Webite" # the name of your site, e.g. ACME Corp.


navigation:
- text: Home
  url: /
- text: Publications
  url: /publications/
