url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Hao Wu's Personal Webite" # the name of your site, e.g. ACME Corp.
# sass:
#   sass_dir: assets/css
